"""empty message

Revision ID: 4badbcc638bf
Revises: e2cd95349623
Create Date: 2019-08-20 01:54:14.455156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4badbcc638bf'
down_revision = 'e2cd95349623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'important')
    # ### end Alembic commands ###
